# Generated by Tasker - DO NOT EDIT
# Source: .tasker/config.yml + .tasker/tasks/*.yml
# Regenerate with: tasker generate

-include .env
export

.PHONY: help appnix-dev-all appnix-dev-build appnix-dev-desktop appnix-dev-install appnix-dev-list appnix-dev-reinstall appnix-dev-setup appnix-dev-uninstall lint-dev-check lint-dev-fix lint-dev-format npm-dev-clean npm-dev-compile npm-dev-install tasker-export tasker-generate tasker-init tasker-list tasker-validate tasker-version test-dev-coverage test-dev-e2e test-dev-unit test-dev-watch

.DEFAULT_GOAL := help

help: ## Show available targets
	@echo "appnix - AppNix CLI — convert websites to Linux desktop apps (.deb)"
	@echo ""
	@echo "AppNix  Build, install and manage .deb desktop applications"
	@echo "  appnix-dev-all                 Build all apps and generate desktop entries"
	@echo "  appnix-dev-build               Build .deb packages for all configured apps"
	@echo "  appnix-dev-desktop             Generate .desktop entries for all configured apps"
	@echo "  appnix-dev-install             Build and install a single app by name"
	@echo "  appnix-dev-list                Show all installed AppNix applications"
	@echo "  appnix-dev-reinstall           Uninstall and rebuild a single app"
	@echo "  appnix-dev-setup               Compile TypeScript and install AppNix CLI to ~/.config/appnix"
	@echo "  appnix-dev-uninstall           Remove an installed app and its .deb package"
	@echo ""
	@echo "Lint  Code quality checks and formatting with Biome"
	@echo "  lint-dev-check                 Run Biome linter and formatter checks"
	@echo "  lint-dev-fix                   Run Biome linter with auto-fix"
	@echo "  lint-dev-format                Format source files with Biome"
	@echo ""
	@echo "Node.js  Node.js build, setup and dependency management"
	@echo "  npm-dev-clean                  Remove compiled output directory"
	@echo "  npm-dev-compile                Compile TypeScript source to JavaScript"
	@echo "  npm-dev-install                Install Node.js dependencies"
	@echo ""
	@echo "Tasker  Built-in management commands"
	@echo "  tasker-export                  Export resolved config as Tasker.json"
	@echo "  tasker-generate                Generate Taskfile.yml, Makefile, and Tasker.json"
	@echo "  tasker-init                    Scaffold a new Tasker project"
	@echo "  tasker-list                    Show structured task list"
	@echo "  tasker-validate                Validate Tasker configuration"
	@echo "  tasker-version                 Print version information"
	@echo ""
	@echo "Test  Unit, e2e and coverage testing with Vitest"
	@echo "  test-dev-coverage              Run unit tests with coverage report"
	@echo "  test-dev-e2e                   Run end-to-end tests with Vitest"
	@echo "  test-dev-unit                  Run unit tests with Vitest"
	@echo "  test-dev-watch                 Run unit tests in watch mode"
	@echo ""

appnix-dev-all: ## Build all apps and generate desktop entries
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:all requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix all

appnix-dev-build: ## Build .deb packages for all configured apps
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:build requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix build

appnix-dev-desktop: ## Generate .desktop entries for all configured apps
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:desktop requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix desktop

appnix-dev-install: ## Build and install a single app by name
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:install requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix install {{.CLI_ARGS}}

appnix-dev-list: ## Show all installed AppNix applications
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:list requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix list

appnix-dev-reinstall: ## Uninstall and rebuild a single app
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:reinstall requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix reinstall {{.CLI_ARGS}}

appnix-dev-setup: ## Compile TypeScript and install AppNix CLI to ~/.config/appnix
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:setup requires ENV=dev (current: $$ENV)"; exit 1; fi
	npm run setup

appnix-dev-uninstall: ## Remove an installed app and its .deb package
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task appnix:dev:uninstall requires ENV=dev (current: $$ENV)"; exit 1; fi
	appnix uninstall {{.CLI_ARGS}}

lint-dev-check: ## Run Biome linter and formatter checks
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task lint:dev:check requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx biome check .

lint-dev-fix: ## Run Biome linter with auto-fix
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task lint:dev:fix requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx biome check --fix .

lint-dev-format: ## Format source files with Biome
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task lint:dev:format requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx biome format --write .

npm-dev-clean: ## Remove compiled output directory
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task npm:dev:clean requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx rimraf dist

npm-dev-compile: ## Compile TypeScript source to JavaScript
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task npm:dev:compile requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx tsc && npx tsc-alias

npm-dev-install: ## Install Node.js dependencies
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task npm:dev:install requires ENV=dev (current: $$ENV)"; exit 1; fi
	npm install

tasker-export: ## Export resolved config as Tasker.json
	tasker export

tasker-generate: ## Generate Taskfile.yml, Makefile, and Tasker.json
	tasker generate

tasker-init: ## Scaffold a new Tasker project
	tasker init

tasker-list: ## Show structured task list
	tasker list

tasker-validate: ## Validate Tasker configuration
	tasker validate

tasker-version: ## Print version information
	tasker version

test-dev-coverage: ## Run unit tests with coverage report
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task test:dev:coverage requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx vitest run --watch=false tests/unit --coverage

test-dev-e2e: ## Run end-to-end tests with Vitest
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task test:dev:e2e requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx vitest run --watch=false tests/e2e

test-dev-unit: ## Run unit tests with Vitest
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task test:dev:unit requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx vitest run --watch=false tests/unit

test-dev-watch: ## Run unit tests in watch mode
	@if [ -n "$$ENV" ] && [ "$$ENV" != "dev" ]; then echo "Task test:dev:watch requires ENV=dev (current: $$ENV)"; exit 1; fi
	npx vitest watch tests/unit

